# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:41
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=accounts.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('NONE', 'NONE'), ('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
