# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170801_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=10),
        ),
    ]
